### ISSUE TITLE
Test documentation examples result in an error

### ISSUE THREAD

**Issue by tjalkane** [CSCfi/ansible-role-users#38] opened 2017-10-10 10:54 UTC
Following examples found under tests/test.yml result in errors during the "Add or remove ssh keys and use key_options if option is used" task. However, changing group option to groups in adminusers fixes the problem.

**Comment by martbhell** [comment] 2017-10-10 10:59
I think we'll need more details like exact errors, ansible version and role version :)
The  "Add or remove ssh keys and use key_options if option is used"  should not use any group or groups variables or parameters.

**Comment by tjalkane** [comment] 2017-10-11 08:05
I'm using ansible version 2.4.0.0 and the latest version of ansible-role-users. This is the error that I get from the task that fails: 
```
failed: [<hostname>] (item=timo) => {"changed": false, "failed": true, "msg": "Failed to lookup user timo: 'getpwnam(): name not found: timo'", "user": {"group": "admin", "name": "timo", "pubkey": “this had key info in it”, "shell": "/bin/bash", "state": "present", "uid": 5001}}
```

**Comment by martbhell** [comment] 2017-10-11 11:41
Managed to reproduce this. Think it's a typo in a conditional. If one would have looked carefully in https://travis-ci.org/CSCfi/ansible-role-users/jobs/286443421#L1833 one could have seen that the first play in test.yml actually doesn't add any users! Also further down the UIDs are not what we set them to in test.yml

Because it looks to me like this role is mostly broken right now I 
 pushed to master in e14a52aa060e4039bf1d85bb9f8c6a54a10c4bc1

Before this the main add user task could only add a user if the UID was not defined, or if UID was set but only for the ansible_ssh_user

This changes it so that main add user task can add a user if the UID is undefined or if the UID is set but _not_ for ansible_ssh_user

---

While doing some testing in relation it  seems that this change again broke the "cannot change UID of logged in users". I've submitted a #41 for that.

I'll close this for now as it seems to be working for me.

**Closed by martbhell** 2017-10-11 11:41 UTC
Labels: bug, in progress
